#! /bin/bash
# extract: Archive Extractor
# Bob Holden, EAWF.COM
v.0.02 - 20170703
# ======================================
if [ -z "$1" ]; then
 echo
 echo "extract - Extracts Archive File (Fails if Archiver not installed.)"
 echo
 echo "Usage: extract [path/]file [r]"
 echo "  path/file = Known archive types:(zip|rar|bz2|gz|tar|tbz2|tgz|Z|7z|xz|ex|tar.bz2|tar.gz|tar.xz)"
 echo "  r = removes archive "
 echo
 exit 1
else
 if [ -f $1 ] ; then
  # NAME=${1%.*} mkdir $NAME && cd $NAME
  case $1 in
   *.tar.bz2) tar xvjf $1 ;;
   *.tar.gz) tar xvzf $1 ;;
   *.tar.xz) tar xvJf $1 ;;
   *.lzma) unlzma $1 ;;
   *.bz2) bunzip2 $1 ;;
   *.rar) unrar x -ad $1 ;;
   *.gz) gunzip $1 ;;
   *.tar) tar xvf $1 ;;
   *.tbz2) tar xvjf $1 ;;
   *.tgz) tar xvzf $1 ;;
   *.zip) unzip $1 ;;
   *.Z) uncompress $1 ;;
   *.7z) 7z x $1 ;;
   *.xz) unxz $1 ;;
   *.exe) cabextract $1 ;;
   *) echo
      echo "FAIL: $1 - unknown archive method"
      echo
      exit 1 ;;
  esac
  if [ -e $2 -a "$2" == "r"]
   rm $1
  fi
 else
  echo "Archive $1 does not exist"
 fi
fi
# Done

