#! /bin/bash
# vimp: Manage Editing of Files
# Bob Holden, EAWF.COM
# Modification to use vi instead of nano
# v.1.12 - 20170516
# ======================================
if [ -f $1 ]; then
 cp $1 $1.bak
 vi $1.bak
 diff -q $1 $1.bak > /dev/nul
 if [ $? -gt 0 ]; then
  mv $1 $1.$(date +"%Y%m%d%H%M%S")
  cp $1.bak $1
  echo -e "\e[1m\e[34mFile Modified.\e[0m"
 else
  echo -e "\e[1m\e[35mFile NOT Modified.\e[0m"
 fi
 rm $1.bak
else
# echo -e "\e[1m\e[35mFile $1 NOT Found!\e[0m"
 vi $1
fi
# Done

